server:
  port: 9000


elasticsearch:
  host: 43.142.251.73
  port: 9200
  username:
  password:

spring:
  datasource:
    url: jdbc:mysql://172.19.81.34:3307/sys_bank_web?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: speech@10jqka
    name: sys_bank_web
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  config: config/logback.xml

rabbit:
  host: 43.142.251.73:5672
  username: admin
  password: admin
